CREATE TABLE `prioridade` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`prioridade` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
